image: node

build:
  stage: build
  variables:
    PUBLIC_URL: https://iit-projektschiene.pages.fhnw.ch/FS23/ip5_inserate-one11/
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
